### ISSUE TITLE
consider migrating to Postgres

### ISSUE THREAD

**Issue by dreikanter** [dreikanter/boodka#20]
``` yaml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432

development:
  <<: *default
  database: "<%= ENV['app_name'] %>_development"

test:
  <<: *default
  database: "<%= ENV['app_name'] %>_test"

production:
  <<: *default
  host: "<%= ENV['postgres_host'] %>"
  port: "<%= ENV['postgres_port'] %>"
  database: "<%= ENV['app_name'] %>"
  username: "<%= ENV['postgres_username'] %>"
  password: "<%= ENV['postgres_password'] %>"

staging:
  <<: *default
  host: "<%= ENV['postgres_host'] %>"
  port: "<%= ENV['postgres_port'] %>"
  database: "<%= ENV['postgres_database'] %>"
  username: "<%= ENV['postgres_username'] %>"
  password: "<%= ENV['postgres_password'] %>"
```
